package com.codemonk.documentation.domain;

/**
 * Enumeration representing supported types of architectural documentation generated by CodeMonk.
 */
public enum DocType {
    ARCHITECTURE,
    API_OVERVIEW,
    COMPONENT_SUMMARY,
    DEPENDENCY_GRAPH
}
